//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int ID_Livro { get; set; }
        public string Titulo { get; set; }
        public string Editora { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Autor { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> Categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
